spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb
    username: root
    password: secure

mybatis:  configuration:    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.model